"""Public enum contracts for Reality Gap records."""

from enum import Enum


class RealityGapDimension(str, Enum):
    MARKET = "MARKET"
    INTELLIGENCE = "INTELLIGENCE"
    OBSERVABILITY = "OBSERVABILITY"
    EXPLANATION = "EXPLANATION"
    UNKNOWN = "UNKNOWN"


class RealityGapPrimaryType(str, Enum):
    NO_GAP = "NO_GAP"
    MISSING_EXPECTED_REALITY = "MISSING_EXPECTED_REALITY"
    UNEXPECTED_REALITY = "UNEXPECTED_REALITY"
    CONTRADICTORY_REALITY = "CONTRADICTORY_REALITY"
    MIXED_GAP = "MIXED_GAP"
    OBSERVABILITY_GAP = "OBSERVABILITY_GAP"
    EXPLANATION_GAP = "EXPLANATION_GAP"
    UNKNOWN = "UNKNOWN"


class IntelligenceGapType(str, Enum):
    DETECTION_GAP = "DETECTION_GAP"
    INTERPRETATION_GAP = "INTERPRETATION_GAP"
    CORRELATION_GAP = "CORRELATION_GAP"
    EXPECTATION_FORMATION_GAP = "EXPECTATION_FORMATION_GAP"
    CONFIDENCE_CALIBRATION_GAP = "CONFIDENCE_CALIBRATION_GAP"
    POLICY_COVERAGE_GAP = "POLICY_COVERAGE_GAP"
    UNKNOWN = "UNKNOWN"


class ObservabilityGapType(str, Enum):
    MISSING_PROVIDER_INPUT = "MISSING_PROVIDER_INPUT"
    STALE_DATA = "STALE_DATA"
    UNSUPPORTED_FACTOR = "UNSUPPORTED_FACTOR"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    LOW_COVERAGE = "LOW_COVERAGE"
    POOR_DATA_QUALITY = "POOR_DATA_QUALITY"
    INSUFFICIENT_EVALUATION_WINDOW = "INSUFFICIENT_EVALUATION_WINDOW"
    TIMESTAMP_INCONSISTENCY = "TIMESTAMP_INCONSISTENCY"
    IDENTITY_OR_LINEAGE_GAP = "IDENTITY_OR_LINEAGE_GAP"
    UNKNOWN = "UNKNOWN"


class RealityGapSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RootCauseCategory(str, Enum):
    FACTOR_WEAKENING = "FACTOR_WEAKENING"
    FACTOR_DISAPPEARANCE = "FACTOR_DISAPPEARANCE"
    FACTOR_NON_CONFIRMATION = "FACTOR_NON_CONFIRMATION"
    FACTOR_CONTRADICTION = "FACTOR_CONTRADICTION"
    STAGE_REGRESSION = "STAGE_REGRESSION"
    STAGE_STAGNATION = "STAGE_STAGNATION"
    MATURITY_WITHOUT_CONFIRMATION = "MATURITY_WITHOUT_CONFIRMATION"
    AVAILABILITY_DEGRADATION = "AVAILABILITY_DEGRADATION"
    OBSERVABILITY_LIMITATION = "OBSERVABILITY_LIMITATION"
    INTELLIGENCE_LIMITATION = "INTELLIGENCE_LIMITATION"
    UNKNOWN = "UNKNOWN"


class RootCauseRole(str, Enum):
    PRIMARY_CANDIDATE = "PRIMARY_CANDIDATE"
    CONTRIBUTING_CANDIDATE = "CONTRIBUTING_CANDIDATE"
    CONTEXT_CANDIDATE = "CONTEXT_CANDIDATE"
    ALTERNATIVE_CANDIDATE = "ALTERNATIVE_CANDIDATE"
    REJECTED_CANDIDATE = "REJECTED_CANDIDATE"


class RootCauseDisposition(str, Enum):
    ACCEPTED = "ACCEPTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    REJECTED = "REJECTED"
    UNRESOLVED = "UNRESOLVED"


class RealityGapEvidenceType(str, Enum):
    EXPECTATION_BASIS = "EXPECTATION_BASIS"
    EVALUATION_FACT = "EVALUATION_FACT"
    TIMELINE_ENTRY = "TIMELINE_ENTRY"
    SITUATION_DNA = "SITUATION_DNA"
    DNA_DELTA = "DNA_DELTA"
    STAGE_CHANGE = "STAGE_CHANGE"
    AVAILABILITY_CHANGE = "AVAILABILITY_CHANGE"
    IDENTITY_TRACE = "IDENTITY_TRACE"
    EVOLUTION_TRACE = "EVOLUTION_TRACE"
    OBSERVABILITY_FACT = "OBSERVABILITY_FACT"


class RealityGapEvidenceRelation(str, Enum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    PRECEDES = "PRECEDES"
    FOLLOWS = "FOLLOWS"
    EXPLAINS = "EXPLAINS"
    LIMITS_EXPLANATION = "LIMITS_EXPLANATION"
    ALTERNATIVE_TO = "ALTERNATIVE_TO"
    UNRELATED = "UNRELATED"


class RealityGapEvidenceEligibility(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"


__all__ = [
    "IntelligenceGapType",
    "ObservabilityGapType",
    "RealityGapDimension",
    "RealityGapEvidenceEligibility",
    "RealityGapEvidenceRelation",
    "RealityGapEvidenceType",
    "RealityGapPrimaryType",
    "RealityGapSeverity",
    "RootCauseCategory",
    "RootCauseDisposition",
    "RootCauseRole",
]
